### ISSUE TITLE
Signup page throws 404 Not found error

### ISSUE THREAD

**Issue by tungbq** [unitaryfund/unitaryhack#11]
Signup page throws 404 Not found error
**URL:** https://unitaryhack.dev/signup/
![image](https://github.com/unitaryfund/unitaryhack/assets/85242618/9470f333-6f99-4f3f-a3ae-d054b4d0e506)

**Comment by natestemen** [comment]
Thanks for the issue! Where did you find a link to this page? It's not used on the current website, so we removed it.

**Comment by tungbq** [comment]
It's in the `After the Hack` section of https://unitaryhack.dev/hacker-guide/
![image](https://github.com/unitaryfund/unitaryhack/assets/85242618/640f333f-e97b-4bd9-b104-15056d0ba0e8)
